/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BlogShop } from "./BlogShop";
export type { JTCoin } from "./JTCoin";
export type { Lock } from "./Lock";
