/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface InfoContractInterface extends Interface {
  getFunction(
    nameOrSignature: "getInfo" | "getInfo2" | "sayHi" | "setInfo"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Instruction"): EventFragment;

  encodeFunctionData(functionFragment: "getInfo", values?: undefined): string;
  encodeFunctionData(functionFragment: "getInfo2", values?: undefined): string;
  encodeFunctionData(functionFragment: "sayHi", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setInfo",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getInfo2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sayHi", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setInfo", data: BytesLike): Result;
}

export namespace InstructionEvent {
  export type InputTuple = [name: string, arg1: BigNumberish];
  export type OutputTuple = [name: string, arg1: bigint];
  export interface OutputObject {
    name: string;
    arg1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InfoContract extends BaseContract {
  connect(runner?: ContractRunner | null): InfoContract;
  waitForDeployment(): Promise<this>;

  interface: InfoContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getInfo: TypedContractMethod<[], [[string, bigint]], "view">;

  getInfo2: TypedContractMethod<[], [bigint], "view">;

  sayHi: TypedContractMethod<[], [string], "view">;

  setInfo: TypedContractMethod<
    [_name: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getInfo"
  ): TypedContractMethod<[], [[string, bigint]], "view">;
  getFunction(
    nameOrSignature: "getInfo2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sayHi"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setInfo"
  ): TypedContractMethod<
    [_name: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Instruction"
  ): TypedContractEvent<
    InstructionEvent.InputTuple,
    InstructionEvent.OutputTuple,
    InstructionEvent.OutputObject
  >;

  filters: {
    "Instruction(string,uint256)": TypedContractEvent<
      InstructionEvent.InputTuple,
      InstructionEvent.OutputTuple,
      InstructionEvent.OutputObject
    >;
    Instruction: TypedContractEvent<
      InstructionEvent.InputTuple,
      InstructionEvent.OutputTuple,
      InstructionEvent.OutputObject
    >;
  };
}
